### PR TITLE
Replacement for previous pull request adding an initial Blender model

### PR DESCRIPTION
**Pull request by TrevorSmale**
This pull request is a follow-up to my last request to include an initial Blender model. The previous request was abandoned due to the location of the new folder. This request includes the same files as the last request with a change to the Blender folder location.

This initial Blender model commit includes a master Blender file with all included dependencies along with a few sample renderings depicting the current rendering output parameters.

The model was created using project CAD files and procedurally textured in Blender 2.91. Render settings create a PNG with transparent background suitable for graphic publication.

### CODE REVIEW

**Comment by chipaudette** [comment]
@biomurph and @eyuan-creare ,

Look good to you?

**Comment by eyuan-creare** [comment]
@TrevorSmale Thanks again for these beautiful renders!  
 It looks like the power switch and potentiometer are labeled wrong.  Is this easy to correct?

image

**Comment by TrevorSmale** [comment]
@eyuan-creare Thank you, I appreciate the compliment. You are right, thanks for pointing that out. @biomurph please cancel this pull request, I will fix this issue and resubmit.

**Comment by TrevorSmale** [comment]
@biomurph nevermind, I have the option to close on my own :)

**Pull request closed without merging**
