### PR TITLE
Added initial Blender model

### PR DESCRIPTION
**Pull request by TrevorSmale**
I created the initial Blender model utilizing the original .KiCAD board files and enclosure .STP files from the repo combined with elements modelled and textured within Blender 2.91 using procedural texturing methods. Text leaders and leader lines are rigged to face the camera at all times for rendering at almost any angle. Textures and components have adjustable visibility and transparency for generating many view combinations. The rendering output settings create a high res .PNG file with transparent background suited to graphic layout. The Blender file has all external assets included and the asset browser is fairly well organized.

### CODE REVIEW

**Comment by chipaudette** [comment]
@biomurph , @eyuan-creare ,

These are very attractive!  I don't have any experience incorporating this kind of information in a repo, however.  Do either of you have the experience to confirm that the way that this is included in the repo is satisfactory?

**Comment by biomurph** [comment]
@TrevorSmale This is great work!
I would like to go over it prior to merging.
I may have some questions and I'll raise them with you on your fork.

@chipaudette I am not sure I understand your question. I think that the blender model and related files are contained in their own folder. I would think that if anything, we should think about the file structure. Right now, those files are located in the KiCad folder. Might be better to have the in their own higher level 'blender' folder?

**Comment by eyuan-creare** [comment]
@TrevorSmale This is beautiful modelling! Nice work. 👏

If you are willing to share, what application are you using the Tympan for?

**Comment by chipaudette** [comment]
@TrevorSmale , what do you think of the suggestion of @biomurph regarding the folder structure of the repo?  Do you think it's best to put your Blender stuff in the KiCad directory, or should it be pulled out and put in a higher level "Blender" (or whatever) directory.  Thoughts?

**Comment by TrevorSmale** [comment]
@biomurph @chipaudette I should have given more thought to the folder location, it is a good idea to discuss the convention. I do agree that it should be at a higher level in a seperate directory. Maybe I should re-submit a pull request when we have discussed a better directory structure for this. Currently everything is self contained / packed into one file. However, typically a 3D scene such as this should be stored in a folder with a relative path to dependencies like images and CAD files much like a website directory has an img and css folder.

@eyuan-creare I am not using the Tympan for anything at the moment, I just wanted to support the project with my own skill set. The model is designed for virtual photography / rendering to support publication graphics and technical documentation.

**Comment by biomurph** [comment]
@TrevorSmale good idea.
Please withdraw this pull request (or do I have to do that?)
Then re-submit with your work at a higher level.

**Comment by biomurph** [comment]
Oh, I see I can close it.
Closing now.

**Pull request closed without merging**
